export enum ApiURI{
  SIGN_IN='account/signin',
  SIGN_UP='account/signup',
  ME='account/me',
  REFRESH_TOKEN = 'account/refresh',
  DETAIL='profile/detail',
  UPDATE_PROFILE='profile/update',
  PUBLISH = 'publication/publish',
  LIST_PUBLICATION = 'publication/list',
  PUBLICATION_NUMBER = 'publication/user-publications',
  LAST_PUBLICATION = 'publication/last-publication',
  DELETE_PUBLICATION = 'publication/delete/',
  LIST_COMMENT = 'comment/list',
  COMMENT = 'comment/comment',
  COMMENT_NUMBER = 'comment/user-comments',
  LAST_COMMENT = 'comment/last-comment',
  LIKE = 'like/like',
  LIST_LIKE = 'like/list',
  LAST_LIKE = 'like/last-like',
}
